name: flutility
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.17+855

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dak_solutions_common:
    path: C:/Users/tranh/StudioProjects/new/dak_solutions_common
    # path: /Volumes/Macintosh HD/Users/dak/Documents/Github/dak_solutions_common
  ## DATA HANDLE PACKAGES
  # This lib to set windows size on Windows.
  window_manager: ^0.4.2
  http: ^1.2.1
  # A Flutter plugin for finding commonly used locations on the filesystem
  path_provider: ^2.1.3
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.0
  # Save settings
  shared_preferences: ^2.3.2
  ##
  # Package for Packaging Windows App
  msix: ^3.16.8
  # State management combination
  flutter_bloc: ^8.1.6
  # Open link
  url_launcher: ^6.3.0
  # create route for application, it is now 05/05/2024 required to stick to ^12.1.3 to get PopScope to work properly
  go_router: 12.1.3
  collection: ^1.18.0
  # The path package provides common operations for manipulating paths: joining, splitting, normalizing, etc
  path: ^1.9.0
  image_picker: ^1.1.2

  ### UI PACKAGES
  responsive_builder: ^0.7.0
  loading_indicator: ^3.1.1
  # use for customizing theme
  dynamic_color: ^1.7.0
  # localization
  flutter_localization: ^0.2.0
  flutter_localizations:
    sdk: flutter
  i18n_extension: ^12.0.1
  # custom icon
  font_awesome_flutter: ^10.8.0
  flutter_sizer: ^1.0.5
  device_info_plus: ^10.1.2
  flutter_spinkit: ^5.2.1
  http_parser: ^4.0.2
  equatable: ^2.0.5
  file_picker: ^8.0.6
  open_file_plus: ^3.4.1+1
  loading_animation_widget: ^1.2.1
  intl: ^0.19.0
  string_validator: ^1.1.0
  windows_status_bar:
    git: https://github.com/tranhuudang/windows_status_bar
  fluentui_system_icons: ^1.1.273
  dotted_border: ^2.1.0
  google_fonts: ^6.2.1
  image: ^4.3.0
  flex_color_picker: ^3.6.0
  upgrader: ^10.3.0
  flutter_quill: ^10.8.5
  flutter_colorpicker: ^1.1.0
  flutter_svg: ^2.0.17
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  riverpod_generator: ^2.6.5
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  build_runner: ^2.4.15
  freezed: ^3.0.2
  json_serializable: ^6.9.4

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/fluentui-system-icons/
    - assets/release_notes/release_notes.json
    - assets/badges/
    - assets/images/app_icon.png
    - assets/donation/
msix_config:
  display_name: Flutility
  publisher_display_name: DAK Solutions
  identity_name: 24555Zeroboy.FlutterToolkits
  publisher: CN=DA7D2C99-987C-4B69-8953-17157F6E0E1A
  msix_version: 2025.2.22.0
  trim_logo: false
  logo_path: C:\Users\tranh\StudioProjects\FlutterToolkit\assets\images\app_icon.png
  store: true
  language: en-us, vi-vi, zh-cn