// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBplfikX3liDeyFFodRyEWYpBnO9l1Iz6M',
    appId: '1:867146042969:web:18c41d34c3e1a7ae246b48',
    messagingSenderId: '867146042969',
    projectId: 'diccon-evo',
    authDomain: 'diccon-evo.firebaseapp.com',
    databaseURL: 'https://diccon-evo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'diccon-evo.appspot.com',
    measurementId: 'G-Q1PGCCQ9N6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRT6Ys7EvXoCDFc1obebbAwUXi4oBjJkk',
    appId: '1:867146042969:ios:61b0b5aad83b3901246b48',
    messagingSenderId: '867146042969',
    projectId: 'diccon-evo',
    databaseURL: 'https://diccon-evo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'diccon-evo.appspot.com',
    androidClientId: '867146042969-0l2u1i7ug12637rns65p7qihrr9kk8u2.apps.googleusercontent.com',
    iosClientId: '867146042969-bleuvsqh9g14c49voia6bvbg8r5rl3ps.apps.googleusercontent.com',
    iosBundleId: 'com.zeroboy.flutterToolkits',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBplfikX3liDeyFFodRyEWYpBnO9l1Iz6M',
    appId: '1:867146042969:web:56791ca08c4fd07f246b48',
    messagingSenderId: '867146042969',
    projectId: 'diccon-evo',
    authDomain: 'diccon-evo.firebaseapp.com',
    databaseURL: 'https://diccon-evo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'diccon-evo.appspot.com',
    measurementId: 'G-4KWWHJFDJ5',
  );
}
