// List of Google Fonts
final List<String> fontFamilies_1 = [
  'Teko',
  'Merriweather Sans',
  'Noto Serif Display',
  'Fira Sans',
  'Cabin Sketch',
  'Rokkitt',
  'Lora',
  'Hind Siliguri',
  'Arimo',
  'Exo',
  'Coda',
  'Gloock',
  'Overpass Mono',
  'Sora',
  'Assistant',
  'Barlow',
  'Bree Serif',
  'Spectral',
  'Baloo 2',
  'B612',
  'Fira Code',
  'Source Code Pro',
  'Work Sans',
  'Zilla Slab Highlight',
  'Manjari',
  'Karla',
  'DM Sans',
  'Gloock',
  'Quicksand',
  'Oregano',
  'Sanchez',
  'Roboto Mono',
  'Khand',
  'Courgette',
  'Archivo',
  'Noto Sans JP',
  'Noto Sans KR',
  'Noto Sans Display',
  'Dancing Script',
  'Alegreya',
  'Montserrat Alternates',
  'Crimson Text',
  'Lexend',
  'Teko',
  'Varela Round',
  'Vesper Libre',
  'Zilla Slab',
  'Zen Dots',
  'Yeseva One',
  'Zeyada',
  'Tangerine',
  'Cormorant Garamond',
  'Rock Salt',
  'Patrick Hand',
  'Chewy',
  'Creepster',
  'Satisfy',
  'Fjalla One',
  'Pangolin',
  'Tajawal',
  'Karma',
  'Poppins',
  'Hind',
  'Righteous',
  'Sarina',
  'Julius Sans One',
  'Noto Sans',
  'Roboto',
  'Lobster',
  'Open Sans',
  'Montserrat',
  'Oswald',
  'Merriweather',
  'Poppins',
  'Dancing Script',
  'Raleway',
  'Lato',
  'Nunito',
  'Playfair Display',
  'Work Sans',
  'Quicksand',
  'Bebas Neue',
  'Titillium Web',
  'Cinzel',
  'Fjalla One',
  'Karla',
  'Ubuntu',
  'Spectral',
  'Cabin',
  'Abril Fatface',
  'Righteous',
  'Zilla Slab',
  'Pangolin',
  'Rubik',
  'Patua One',
  'Oxygen',
  'Anton',
  'Arvo',
  'Dosis',
  'Satisfy',
  'Alfa Slab One',
  'Lora',
  'Inconsolata',
  'Permanent Marker',
  'Rochester',
  'Cinzel Decorative',
  'Candal',
  'Coda',
  'Dosis',
  'Fjalla One',
  'Gloock',
  'Gochi Hand',
  'Gurajada',
  'Hind',
  'Indie Flower',
  'Julius Sans One',
  'Kanit',
  'Kumar One',
  'Lexend Deca',
  'Lobster Two',
  'Marcellus',
  'Markazi Text',
  'Nanum Gothic',
  'Noto Serif',
  'Overpass',
  'Racing Sans One',
  'Raleway Dots',
  'Red Hat Display',
  'Rubik Wet Paint',
  'Sen',
  'Spectral SC',
  'Tajawal',
  'Tilt Prism',
  'Trispace'
];
